"""adicionando coluna pontuacao na tabela usuário

Revision ID: 100c2a855669
Revises: 447f4ef41624
Create Date: 2023-12-11 20:14:46.518901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100c2a855669'
down_revision = '447f4ef41624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pontuacao', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('pontuacao')

    # ### end Alembic commands ###
