"""o

Revision ID: 2ef520ae4604
Revises: 
Create Date: 2024-09-03 21:11:49.955849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ef520ae4604'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=100), nullable=True),
    sa.Column('pontuacao', sa.Integer(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colecao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('descricao', sa.String(length=120), nullable=True),
    sa.Column('tipo', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repertorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=80), nullable=True),
    sa.Column('conteudo', sa.String(length=10000), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('referencia', sa.String(length=120), nullable=True),
    sa.Column('tipo', sa.String(length=80), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('avaliacao', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=80), nullable=True),
    sa.Column('descricao', sa.String(length=120), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Colecao_repertorio',
    sa.Column('colecao_id', sa.Integer(), nullable=True),
    sa.Column('repertorio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['colecao_id'], ['colecao.id'], ),
    sa.ForeignKeyConstraint(['repertorio_id'], ['repertorio.id'], )
    )
    op.create_table('Tema_repertorio',
    sa.Column('tema_id', sa.Integer(), nullable=True),
    sa.Column('repertorio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repertorio_id'], ['repertorio.id'], ),
    sa.ForeignKeyConstraint(['tema_id'], ['tema.id'], )
    )
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('repertorio_id', sa.Integer(), nullable=True),
    sa.Column('pontuacao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repertorio_id'], ['repertorio.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tema_repertorio',
    sa.Column('tema_id', sa.Integer(), nullable=False),
    sa.Column('repertorio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repertorio_id'], ['repertorio.id'], ),
    sa.ForeignKeyConstraint(['tema_id'], ['tema.id'], ),
    sa.PrimaryKeyConstraint('tema_id', 'repertorio_id')
    )
    op.create_table('tipo_repertorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repertorio_id', sa.Integer(), nullable=True),
    sa.Column('pontuacao', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['repertorio_id'], ['repertorio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tipo_repertorio')
    op.drop_table('tema_repertorio')
    op.drop_table('comentario')
    op.drop_table('Tema_repertorio')
    op.drop_table('Colecao_repertorio')
    op.drop_table('tema')
    op.drop_table('repertorio')
    op.drop_table('colecao')
    op.drop_table('usuario')
    # ### end Alembic commands ###
