"""adicionando tabela tema_repertorio

Revision ID: 5655ba702e44
Revises: 900308b9e4fd
Create Date: 2023-12-21 21:35:53.321432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5655ba702e44'
down_revision = '900308b9e4fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tem_reper',
    sa.Column('tema_id', sa.Integer(), nullable=True),
    sa.Column('repertorio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repertorio_id'], ['repertorio.id'], ),
    sa.ForeignKeyConstraint(['tema_id'], ['tema.id'], )
    )
    op.drop_table('tem_reper')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('admins')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admins', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    op.create_table('tem_repert',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tema_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('repertorio_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['repertorio_id'], ['repertorio.id'], name='tema_repertorio_ibfk_1'),
    sa.ForeignKeyConstraint(['tema_id'], ['tema.id'], name='tema_repertorio_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Tem_reper')
    # ### end Alembic commands ###
