"""adicionando colunas na tabela repertorio

Revision ID: 900308b9e4fd
Revises: 100c2a855669
Create Date: 2023-12-11 20:42:58.510555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900308b9e4fd'
down_revision = '100c2a855669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repertorio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('data', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('avaliacao', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('conteudo', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repertorio', schema=None) as batch_op:
        batch_op.drop_column('conteudo')
        batch_op.drop_column('avaliacao')
        batch_op.drop_column('data')
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
