"""criando tabela colecao_repertorio

Revision ID: a0f683873d88
Revises: 5655ba702e44
Create Date: 2023-12-25 13:47:49.687592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0f683873d88'
down_revision = '5655ba702e44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('Colecao_repertorio',
    sa.Column('colecao_id', sa.Integer(), nullable=True),
    sa.Column('repertorio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['colecao_id'], ['colecao.id'], ),
    sa.ForeignKeyConstraint(['repertorio_id'], ['repertorio.id'], )
    )
    op.drop_table('tema_repertorio')
    with op.batch_alter_table('colecao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=80), nullable=True))
        batch_op.drop_column('titulo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colecao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', mysql.VARCHAR(length=80), nullable=True))
        batch_op.drop_column('nome')

    op.create_table('tema_repertorio',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tema_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('repertorio_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['repertorio_id'], ['repertorio.id'], name='tema_repertorio_ibfk_1'),
    sa.ForeignKeyConstraint(['tema_id'], ['tema.id'], name='tema_repertorio_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Colecao_repertorio')
    op.drop_table('Tema_repertorio')
    # ### end Alembic commands ###
