"""configurando relacionamento na tabela colecao_repertorio

Revision ID: c44bea9949ff
Revises: ed1b17322ed3
Create Date: 2023-12-26 11:32:59.571295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c44bea9949ff'
down_revision = 'ed1b17322ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Colecao_repertorio',
    sa.Column('repertorio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['colecao_id'], ['colecao.id'], ),
    sa.ForeignKeyConstraint(['repertorio_id'], ['repertorio.id'], )
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tema_repertorio',
    sa.Column('my_row_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tema_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('repertorio_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['repertorio_id'], ['repertorio.id'], name='tema_repertorio_ibfk_1'),
    sa.ForeignKeyConstraint(['tema_id'], ['tema.id'], name='tema_repertorio_ibfk_2'),
    sa.PrimaryKeyConstraint('my_row_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Colecao_repertorio')
    # ### end Alembic commands ###
